MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  RPN:
    PRE_NMS_TOPK_TRAIN: 6000
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TRAIN: 300
    POST_NMS_TOPK_TEST: 300
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("vidor_train_16", "vidor_coco_train", "vidor_coco_val_minus_minival", "vidor_ilsvrc_train2013", "vidor_ilsvrc_train2014", )
  TEST: ("vidor_test_16", )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (80000, )
  MAX_ITER: 640000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  DETECTIONS_PER_IMAGE: 300
VERSION: 2